team:
  name: "Team"
  base:
    location: "at dumb burning man"
battle:
  cry: "BATTLE CRY"
flag:
  background: green
  color: goldenrod
  highlight: blue
font:
  family: Helvetica
other_site:
  url: http://facebook.com
